# config.yaml
gcp_project_id: datascience-projects
region: us-central1
display_name: My Google Sheet Agent
description: An ADK agent for managing and querying Google Sheets.

# These are the IDs/names of your secrets in Google Secret Manager
spreadsheet_id_secret_id: BUDGET_SPREADSHEET_ID
service_account_creds_secret_id: GOOGLE_SHEET_CREDENTIALS

# Non-sensitive, general configuration for your Google Sheet structure
default_sheet_name: Sheet1
default_start_expense_row: 7