import json
import os
import requests
from datetime import datetime, timedelta

def get_fmp_key():
    # Replace this with however you fetch your API key
    key = os.environ.get("FMP_API_KEY")
    if not key:
        raise ValueError("Please set the FMP_API_KEY environment variable.")
    return key

def run_backtest(stop_loss_pct=15.0, take_profit_pct=25.0, max_hold_days=30):
    print(f"🚀 BACKTESTING SAVED SIGNALS")
    print(f"Parameters -> EOD Stop Loss: {stop_loss_pct}% | Intraday Take Profit: {take_profit_pct}% | Max Hold: {max_hold_days} days\n")
    
    # Load the signals generated by the LLM
    try:
        with open("signals.json", "r") as f:
            signals = json.load(f)
    except FileNotFoundError:
        print("❌ signals.json not found. Run generate_signals.py first!")
        return

    api_key = get_fmp_key()
    total_pnl = 0.0
    winning_trades = 0
    total_trades = 0

    for signal in signals:
        ticker = signal["ticker"]
        entry_date_str = signal["date"]
        score = signal.get("conviction_score", "?")
        
        entry_date = datetime.strptime(entry_date_str, "%Y-%m-%d")
        max_exit_date = entry_date + timedelta(days=max_hold_days)
        
        url = f"https://financialmodelingprep.com/api/v3/historical-price-full/{ticker}?from={entry_date_str}&to={max_exit_date.strftime('%Y-%m-%d')}&apikey={api_key}"
        
        try:
            historical = requests.get(url).json().get("historical", [])
            if len(historical) < 2:
                print(f"[{entry_date_str}] {ticker} (Score: {score}): Not enough future price data.")
                continue
                
            historical.reverse() # Walk forward in time (oldest to newest)
            entry_price = historical[0]["close"]
            
            stop_loss_price = entry_price * (1 + (stop_loss_pct / 100.0))
            take_profit_price = entry_price * (1 - (take_profit_pct / 100.0))
            
            trade_closed = False
            
            for day in historical[1:]:
                daily_low = day["low"]
                daily_close = day["close"]
                
                # 1. Take Profit (Intraday Low)
                if daily_low <= take_profit_price:
                    actual_profit = ((entry_price - take_profit_price) / entry_price) * 100
                    print(f"[{entry_date_str}] {ticker} (Score: {score}): ✅ WIN (+{actual_profit:.2f}%) on {day['date']}")
                    total_pnl += actual_profit
                    winning_trades += 1
                    trade_closed = True
                    break
                    
                # 2. Stop Loss (End of Day Close)
                elif daily_close >= stop_loss_price:
                    actual_loss = ((entry_price - daily_close) / entry_price) * 100
                    print(f"[{entry_date_str}] {ticker} (Score: {score}): ❌ LOSS ({actual_loss:.2f}%) on {day['date']}")
                    total_pnl += actual_loss
                    trade_closed = True
                    break

            # 3. Time Stop (hit max hold days without hitting SL or TP)
            if not trade_closed:
                final_price = historical[-1]["close"]
                time_stop_pnl = ((entry_price - final_price) / entry_price) * 100
                if time_stop_pnl > 0:
                    print(f"[{entry_date_str}] {ticker} (Score: {score}): ⏳ TIME STOP WIN (+{time_stop_pnl:.2f}%)")
                    winning_trades += 1
                else:
                    print(f"[{entry_date_str}] {ticker} (Score: {score}): ⏳ TIME STOP LOSS ({time_stop_pnl:.2f}%)")
                total_pnl += time_stop_pnl
                
            total_trades += 1
            
        except Exception as e:
            print(f"Error checking {ticker}: {e}")

    # Final Stats
    print("\n" + "=" * 50)
    print("🏆 BACKTEST COMPLETE")
    print(f"Total Trades Taken: {total_trades}")
    if total_trades > 0:
        print(f"Win Rate: {(winning_trades / total_trades) * 100:.1f}%")
        print(f"Average Return Per Trade: {total_pnl / total_trades:.2f}%")
    print("=" * 50)

if __name__ == "__main__":
    # You can instantly change these numbers and re-run to see how it affects your PnL!
    run_backtest(stop_loss_pct=15.0, take_profit_pct=25.0, max_hold_days=30)