FROM python:3.11-slim

WORKDIR /app

# Copy requirements from the local directory context
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all the folder scripts (including catalyst_job scripts and sec_sync.py)
COPY ./catalyst_job/ .

# 
#Wecho "Running the job script..."
RUN echo "Checking copied files..." && ls -la

# Generic default fallback
CMD ["python", "sync_catalyst_job.py"]