import os
import json
import asyncio
from typing import Dict, Any
from datetime import datetime
import httpx 
import sys

# --- Configuration (Local Codespace Loopback) ---
APP_URL = "http://127.0.0.1:8000"  # Target the local running ADK engine directly
USER_ID = "user"
SESSION_ID = f"session_{datetime.now().strftime('%Y%m%d%H%M%S')}" 
APP_NAME = "short_selling_agent"  # Matches your active agent profile

# --- API Interaction Functions (ASYNC) ---

async def make_request(client: httpx.AsyncClient, method: str, endpoint: str, data: Dict[str, Any] = None) -> httpx.Response:
    """Helper function for raw asynchronous requests to local ADK middleware."""
    headers = {
        "Content-Type": "application/json"
    }
    url = f"{APP_URL}{endpoint}"
    
    try:
        if method.upper() == 'POST':
            response = await client.post(url, headers=headers, json=data)
        elif method.upper() == 'DELETE':
             response = await client.delete(url, headers=headers)
        else:
            raise ValueError(f"Unsupported method: {method}")

        response.raise_for_status() 
        return response
    except httpx.HTTPStatusError as errh:
        print(f"\n❌ **HTTP ERROR:** Status {response.status_code} for {url}")
        print(f"❌ **Server Response (Raw):**\n{response.text}")
        raise
    except httpx.RequestError as err:
        print(f"\n❌ An unexpected request error occurred: {err}")
        raise

async def run_agent_request(client: httpx.AsyncClient, session_id: str, message: str):
    """Executes a single POST request to the /run_sse endpoint and processes the stream."""
    
    print(f"\n[User] -> Querying LeadQuantTrader with prompt summary...")
    
    run_data = {
        "app_name": APP_NAME,
        "user_id": USER_ID,
        "session_id": session_id,
        "new_message": {"role": "user", "parts": [{"text": message}]},
        "streaming": False 
    }
    
    try:
        response = await make_request(client, "POST", "/run_sse", data=run_data)
        raw_text = response.text.strip()
        
        # Multi-line SSE parsing logic
        data_lines = [
            line.strip() 
            for line in raw_text.split('\n') 
            if line.strip().startswith("data:")
        ]
        
        if not data_lines:
             raise json.JSONDecodeError("No 'data:' lines found in 200 response.", raw_text, 0)
        
        last_data_line = data_lines[-1]
        json_payload = last_data_line[len("data:"):].strip()
        agent_response = json.loads(json_payload)
        
        # Extract the final text summary generated by the LeadQuantTrader
        final_text = agent_response.get('content', {}).get('parts', [{}])[0].get('text', 'Agent response structure not recognized.')
        
        print("\n📝 ================== LEAD QUANT TRADER RECOMMENDATION ==================")
        print(final_text)
        print("=========================================================================\n")
    
    except json.JSONDecodeError as e:
        print(f"\n🚨 **JSON PARSING FAILED**!")
        print(f"   Error: {e}")
        print("   --- RAW SERVER CONTENT ---")
        print(raw_text)
        print("   --------------------------")
    except Exception as e:
        print(f"❌ Agent request failed: {e}")

# --- Main Logic (ASYNC) ---

async def amain(dossier_data_str: str):
    print(f"\n🤖 Starting Single-Run Client | Session: **{SESSION_ID}**")
    
    session_data = {"state": {}}
    current_session_endpoint = f"/apps/{APP_NAME}/users/{USER_ID}/sessions/{SESSION_ID}"
    
    async with httpx.AsyncClient(timeout=120.0) as client: # Generous timeout for deep data evaluation
        
        # 1. Create Session locally (Bypasses 403 because it uses 127.0.0.1)
        try:
            await make_request(client, "POST", current_session_endpoint, data=session_data)
            print(f"✅ Local session created successfully.")
        except Exception as e:
            print(f"❌ Could not start local session: {e}")
            return

        # 2. Run Single Request passing the full historical text dossier
        print(f"--- 💬 Injecting PipelineDossier State Vector ---")
        try:
            prompt = f"""
            Analyze the following PipelineDossier. 
            Identify the market losers, cross-reference them with the news context blocks, and process the quant signals.
            Provide your final short recommendations or structural conclusions.
            
            Dossier Data context:
            {dossier_data_str}
            """
            await run_agent_request(client, SESSION_ID, prompt)
        except Exception as e:
            print(f"❌ Agent execution error: {e}")
        
        # 3. Cleanup: Delete Session
        await asyncio.sleep(1) 
        print(f"## 3. Cleaning Up Local Session: {SESSION_ID}")
        try:
            await make_request(client, "DELETE", current_session_endpoint)
            print("✅ Session deleted cleanly.")
        except Exception as e:
            print(f"⚠️ Warning: Failed to delete session. {e}")

if __name__ == "__main__":
    if sys.version_info < (3, 9):
        print("🚨 ERROR: Python 3.9+ required.")
        sys.exit(1)
        
    # --- LOAD LAST WEEK'S HISTORICAL DOSSIER ---
    # Put your test dossier file path here
    DOSSIER_FILE = "pipeline_dossier_last_week.json" 
    
    try:
        with open(DOSSIER_FILE, "r") as f:
            dossier_content = f.read()
    except FileNotFoundError:
        # Fallback placeholder if file is not generated yet so the script runs cleanly
        dossier_content = json.dumps({
            "market_losers": [{"ticker": "FAKE", "change_percent": -16.5}],
            "news_reports": [],
            "as_of_date": "2026-05-15"
        })
        print(f"⚠️ {DOSSIER_FILE} not found. Running with mock catalyst structure.")

    try:
        asyncio.run(amain(dossier_content))
    except Exception as e:
        print(f"FATAL ERROR: {e}")