from pydantic import BaseModel, Field
from typing import List, Dict, Union, Any
import random
import time
from datetime import date

# --- Pydantic Data Models (Communication Protocol) ---
# Pydantic models enforce the structure of data passed between agents.
class DataPointerModel(BaseModel):
    """Pointer to a data file, storing its location and context."""
    uri: str = Field(description="The file URI (local path or cloud storage) of the data.")
    market: str = Field(description="The market this data pertains to (e.g., 'Gold Futures').")
    
class CftcFutureModel(BaseModel):
    """Model representing a CFTC future search result."""
    future_name: str = Field(alias='name', description="Name of the future contract.")
    market_code: str = Field(alias='code', description="Market code associated with the future.")
    category: str = Field(description="Category of the future.")
    
class RawDataModel(BaseModel):
    """Data ingested by the DataIngestionAgent, containing raw COT and VIX figures."""
    market: str = Field(..., description="The financial market being analyzed (e.g., Gold, S&P 500).")
    cot_net_position: int = Field(..., description="Raw Net Non-Commercial (speculator) position.")
    vix_level: float = Field(..., description="Current VIX or Volatility Index level.")
    date: str = Field(..., description="The date of the data snapshot.")

class FeatureDataModel(BaseModel):
    """Processed features created by the FeatureEngineeringAgent."""
    market: str
    cot_z_score: float = Field(..., description="The Z-Score of the COT net position (e.g., 3-year lookback).")
    vix_percentile: float = Field(..., description="The current VIX level percentile (0-100).")
    feature_summary: str = Field(..., description="Human-readable summary of calculated features.")

class SignalDataModel(BaseModel):
    """Final output signal generated by the SignalGenerationAgent."""
    market: str
    signal: str = Field(..., description="The final trading signal (e.g., 'Strong Buy', 'Neutral', 'Sell').")
    confidence: float = Field(..., description="Confidence level (0.0 to 1.0).")
    justification: str = Field(..., description="Detailed explanation for the signal.")

from pydantic import BaseModel, Field
from datetime import date

class NewFeatureDataModel(BaseModel):
    """
    Defines the structure of the engineered data output by the feature_engineering_tool.
    This model includes calculated features and the final binary signals.
    """
    
    # --- 🔑 Identity and Date ---
    trade_date: date = Field(description="The date corresponding to the feature calculation.")
    
    # --- 📈 VIX Technical Features ---
    # These are the calculated features, NOT the raw price.
    vix_index_level: float = Field(description="The VIX Index closing price on the trade_date.")
    vix_zscore_60d: float = Field(description="VIX Z-Score relative to its 60-day mean/std deviation.")
    vix_vix3m_ratio: float = Field(description="Ratio of VIX Index to VIX 3-Month Future (Term Structure measure).")
    
    # --- 🐻 COT Fundamental Features ---
    # These are the calculated features, NOT the raw Net Position.
    cot_net_position_index: float = Field(
        description="Non-Commercial Net Position normalized to its historical (e.g., 3-year) range (0 to 1)."
    )
    
    # --- 🔥 Dynamic Binary Signals (The LLM's Strategy) ---
    # These are the final signals created using the LLM-defined thresholds (e.g., Z > 2.5, P < 0.05).
    extreme_vix_signal: int = Field(
        description="Binary signal (1 or 0) indicating VIX Z-Score crossed the LLM-defined threshold.",
        ge=0, le=1
    )
    extreme_cot_signal: int = Field(
        description="Binary signal (1 or 0) indicating COT Index crossed the LLM-defined percentile threshold.",
        ge=0, le=1
    )
    
    # --- 🎯 Combined Prediction Feature ---
    # A feature that combines both criteria, ready for the Signal Agent to use.
    vix_crash_trigger: int = Field(
        description="Final combined trigger signal (1 or 0): True when both Extreme VIX and Extreme COT signals are active.",
        ge=0, le=1
    )

