from pydantic import BaseModel, Field
from typing import List, Dict, Union, Any
import random
import time

# --- Pydantic Data Models (Communication Protocol) ---
# Pydantic models enforce the structure of data passed between agents.

class CftcFutureModel(BaseModel):
    """Model representing a CFTC future search result."""
    future_name: str = Field(alias='name', description="Name of the future contract.")
    market_code: str = Field(alias='code', description="Market code associated with the future.")
    category: str = Field(description="Category of the future.")
    
class RawDataModel(BaseModel):
    """Data ingested by the DataIngestionAgent, containing raw COT and VIX figures."""
    market: str = Field(..., description="The financial market being analyzed (e.g., Gold, S&P 500).")
    cot_net_position: int = Field(..., description="Raw Net Non-Commercial (speculator) position.")
    vix_level: float = Field(..., description="Current VIX or Volatility Index level.")
    date: str = Field(..., description="The date of the data snapshot.")

class FeatureDataModel(BaseModel):
    """Processed features created by the FeatureEngineeringAgent."""
    market: str
    cot_z_score: float = Field(..., description="The Z-Score of the COT net position (e.g., 3-year lookback).")
    vix_percentile: float = Field(..., description="The current VIX level percentile (0-100).")
    feature_summary: str = Field(..., description="Human-readable summary of calculated features.")

class SignalDataModel(BaseModel):
    """Final output signal generated by the SignalGenerationAgent."""
    market: str
    signal: str = Field(..., description="The final trading signal (e.g., 'Strong Buy', 'Neutral', 'Sell').")
    confidence: float = Field(..., description="Confidence level (0.0 to 1.0).")
    justification: str = Field(..., description="Detailed explanation for the signal.")

